name: Run Bot Every 6 Hours

on:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir çalışacak
  workflow_dispatch:  # Manuel tetikleme

permissions:
  contents: write  # repo içeriklerine yazma izni veriyoruz

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cloudscraper requests

    - name: Run bot
      run: |
        python channels.py  # Botu çalıştırıyoruz

    - name: Commit the M3U file to the repository
      run: |
        git config --global user.name "github-actions[bot]"  # GitHub Actions botu
        git config --global user.email "github-actions[bot]@users.noreply.github.com"  # Email adresi
        git add rectv_kanallar.m3u  # Ana dizine kaydedilen dosyayı ekliyoruz
        git commit --amend --no-edit --date "$(date)"  # Dosyayı her zaman değiştiriyoruz
        git push origin main --force  # Değişiklikleri GitHub'a gönderiyoruz
