name: Run M3U Python Scripts (TRT 00:00)

on:
  schedule:
    # GitHub Actions CRON UTC çalışır. İstanbul 00:00 = UTC 21:00 (aynı günün -3 saati)
    - cron: "0 21 * * *"
  workflow_dispatch: {}   # İstersen manuel de tetikleyebilirsin

permissions:
  contents: write   # Çıktıları depoya yazıp commit edebilmek için

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: m3u   # dosyaların bu klasörde; gerekirse değiştir
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set timezone (Europe/Istanbul) for runtime
        run: |
          sudo apt-get update
          sudo apt-get install -y tzdata
          sudo ln -fs /usr/share/zoneinfo/Europe/Istanbul /etc/localtime
          echo "Europe/Istanbul" | sudo tee /etc/timezone
          date

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (optional)
        if: hashFiles('m3u/requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # PY dosyalarında boşluk ve + karakterleri var; hepsini güvenli şekilde tek tek çağırıyoruz.
      - name: Run scripts
        run: |
          python "./Amazon Prime.py"
          python "./Blutv.py"
          python "./Disney+.py"
          python "./Exxen.py"
          python "./Gain.py"
          python "./HBO Max.py"
          python "./Hulu.py"
          python "./Netflix.py"
          python "./Paramount+.py"
          python "./Tabii.py"
          python "./TOD TV.py"
          python "./Unutulmaz Diziler.py"

      # Eğer scriptler çıktı dosyaları üretip depoya yazıyorsa, commit/push et
      - name: Commit & push results (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update M3U outputs ($(date +'%Y-%m-%d %H:%M:%S %Z'))"
            git push
          else
            echo "No changes to commit."
          fi
