name: M3U Botları (00:00 TR)

on:
  schedule:
    # GitHub Actions cron UTC çalışır. Istanbul 00:00 => 21:00 UTC
    - cron: "0 21 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

env:
  PY_VER: "3.11"
  WORKDIR: "m3u"
  COMMIT_USER: "github-actions[bot]"
  COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"

jobs:
  run-bot:
    name: ${{ matrix.bot_name }} Bot
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { bot_name: "Amazon",      file: "Amazon Prime.py",      out_hint: "amazon" }
          - { bot_name: "Blutv",       file: "Blutv.py",             out_hint: "blutv" }
          - { bot_name: "Disney+",     file: "Disney+.py",           out_hint: "disneyplus" }
          - { bot_name: "Exxen",       file: "Exxen.py",             out_hint: "exxen" }
          - { bot_name: "Gain",        file: "Gain.py",              out_hint: "gain" }
          - { bot_name: "HBO Max",     file: "HBO Max.py",           out_hint: "hbomax" }
          - { bot_name: "Hulu",        file: "Hulu.py",              out_hint: "hulu" }
          - { bot_name: "Netflix",     file: "Netflix.py",           out_hint: "netflix" }
          - { bot_name: "Paramount+",  file: "Paramount+.py",        out_hint: "paramountplus" }
          - { bot_name: "Tabii",       file: "Tabii.py",             out_hint: "tabii" }
          - { bot_name: "TOD TV",      file: "TOD TV.py",            out_hint: "todtv" }
          - { bot_name: "Unutulmaz Diziler", file: "Unutulmaz Diziler.py", out_hint: "unutulmaz" }
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set timezone (Europe/Istanbul)
        run: |
          sudo apt-get update
          sudo apt-get install -y tzdata
          sudo ln -fs /usr/share/zoneinfo/Europe/Istanbul /etc/localtime
          echo "Europe/Istanbul" | sudo tee /etc/timezone
          date

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run ${{ matrix.file }}
        run: |
          python "./${{ matrix.file }}"

      # Scriptler dosya üretiyorsa değişiklikleri commit/push eder.
      - name: Commit & push (if changed)
        run: |
          git config user.name  "${{ env.COMMIT_USER }}"
          git config user.email "${{ env.COMMIT_EMAIL }}"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "${{ matrix.bot_name }} Bot output ($(date +'%Y-%m-%d %H:%M:%S %Z'))"
            git push
          else
            echo "No changes to commit."
          fi
